// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: limit/v1/limit.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Limit_CreateLimitOrder_FullMethodName = "/api.limit.v1.Limit/CreateLimitOrder"
	Limit_CancelLimitOrder_FullMethodName = "/api.limit.v1.Limit/CancelLimitOrder"
	Limit_GetLimitOrder_FullMethodName    = "/api.limit.v1.Limit/GetLimitOrder"
	Limit_GetLimitOrders_FullMethodName   = "/api.limit.v1.Limit/GetLimitOrders"
)

// LimitClient is the client API for Limit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LimitClient interface {
	CreateLimitOrder(ctx context.Context, in *CreateLimitOrderRequest, opts ...grpc.CallOption) (*CreateLimitOrderReply, error)
	CancelLimitOrder(ctx context.Context, in *CancelLimitOrderRequest, opts ...grpc.CallOption) (*CancelLimitOrderReply, error)
	GetLimitOrder(ctx context.Context, in *GetLimitOrderRequest, opts ...grpc.CallOption) (*GetLimitOrderReply, error)
	GetLimitOrders(ctx context.Context, in *GetLimitOrdersRequest, opts ...grpc.CallOption) (*GetLimitOrdersReply, error)
}

type limitClient struct {
	cc grpc.ClientConnInterface
}

func NewLimitClient(cc grpc.ClientConnInterface) LimitClient {
	return &limitClient{cc}
}

func (c *limitClient) CreateLimitOrder(ctx context.Context, in *CreateLimitOrderRequest, opts ...grpc.CallOption) (*CreateLimitOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLimitOrderReply)
	err := c.cc.Invoke(ctx, Limit_CreateLimitOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *limitClient) CancelLimitOrder(ctx context.Context, in *CancelLimitOrderRequest, opts ...grpc.CallOption) (*CancelLimitOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelLimitOrderReply)
	err := c.cc.Invoke(ctx, Limit_CancelLimitOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *limitClient) GetLimitOrder(ctx context.Context, in *GetLimitOrderRequest, opts ...grpc.CallOption) (*GetLimitOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLimitOrderReply)
	err := c.cc.Invoke(ctx, Limit_GetLimitOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *limitClient) GetLimitOrders(ctx context.Context, in *GetLimitOrdersRequest, opts ...grpc.CallOption) (*GetLimitOrdersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLimitOrdersReply)
	err := c.cc.Invoke(ctx, Limit_GetLimitOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LimitServer is the server API for Limit service.
// All implementations must embed UnimplementedLimitServer
// for forward compatibility.
type LimitServer interface {
	CreateLimitOrder(context.Context, *CreateLimitOrderRequest) (*CreateLimitOrderReply, error)
	CancelLimitOrder(context.Context, *CancelLimitOrderRequest) (*CancelLimitOrderReply, error)
	GetLimitOrder(context.Context, *GetLimitOrderRequest) (*GetLimitOrderReply, error)
	GetLimitOrders(context.Context, *GetLimitOrdersRequest) (*GetLimitOrdersReply, error)
	mustEmbedUnimplementedLimitServer()
}

// UnimplementedLimitServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLimitServer struct{}

func (UnimplementedLimitServer) CreateLimitOrder(context.Context, *CreateLimitOrderRequest) (*CreateLimitOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLimitOrder not implemented")
}
func (UnimplementedLimitServer) CancelLimitOrder(context.Context, *CancelLimitOrderRequest) (*CancelLimitOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelLimitOrder not implemented")
}
func (UnimplementedLimitServer) GetLimitOrder(context.Context, *GetLimitOrderRequest) (*GetLimitOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLimitOrder not implemented")
}
func (UnimplementedLimitServer) GetLimitOrders(context.Context, *GetLimitOrdersRequest) (*GetLimitOrdersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLimitOrders not implemented")
}
func (UnimplementedLimitServer) mustEmbedUnimplementedLimitServer() {}
func (UnimplementedLimitServer) testEmbeddedByValue()               {}

// UnsafeLimitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LimitServer will
// result in compilation errors.
type UnsafeLimitServer interface {
	mustEmbedUnimplementedLimitServer()
}

func RegisterLimitServer(s grpc.ServiceRegistrar, srv LimitServer) {
	// If the following call pancis, it indicates UnimplementedLimitServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Limit_ServiceDesc, srv)
}

func _Limit_CreateLimitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLimitOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimitServer).CreateLimitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Limit_CreateLimitOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimitServer).CreateLimitOrder(ctx, req.(*CreateLimitOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Limit_CancelLimitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelLimitOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimitServer).CancelLimitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Limit_CancelLimitOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimitServer).CancelLimitOrder(ctx, req.(*CancelLimitOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Limit_GetLimitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLimitOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimitServer).GetLimitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Limit_GetLimitOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimitServer).GetLimitOrder(ctx, req.(*GetLimitOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Limit_GetLimitOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLimitOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimitServer).GetLimitOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Limit_GetLimitOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimitServer).GetLimitOrders(ctx, req.(*GetLimitOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Limit_ServiceDesc is the grpc.ServiceDesc for Limit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Limit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.limit.v1.Limit",
	HandlerType: (*LimitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLimitOrder",
			Handler:    _Limit_CreateLimitOrder_Handler,
		},
		{
			MethodName: "CancelLimitOrder",
			Handler:    _Limit_CancelLimitOrder_Handler,
		},
		{
			MethodName: "GetLimitOrder",
			Handler:    _Limit_GetLimitOrder_Handler,
		},
		{
			MethodName: "GetLimitOrders",
			Handler:    _Limit_GetLimitOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "limit/v1/limit.proto",
}
