// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: copy/v1/copy.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCopyOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`                   // 链id
	UserAddress   string                 `protobuf:"bytes,2,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`       // 用户地址
	TargetAddress string                 `protobuf:"bytes,3,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"` // 目标地址
	PrivateKey    string                 `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`          // 用户私钥
	BizOrderId    string                 `protobuf:"bytes,5,opt,name=biz_order_id,json=bizOrderId,proto3" json:"biz_order_id,omitempty"`        // 业务订单id
	// 跟单策略二选一
	//
	// Types that are valid to be assigned to CopyStrategy:
	//
	//	*CreateCopyOrderRequest_FixedAmount
	//	*CreateCopyOrderRequest_Percentage
	CopyStrategy   isCreateCopyOrderRequest_CopyStrategy `protobuf_oneof:"copy_strategy"`
	FollowSell     bool                                  `protobuf:"varint,8,opt,name=follow_sell,json=followSell,proto3" json:"follow_sell,omitempty"`                    // 是否跟卖
	SellPercentage *float64                              `protobuf:"fixed64,9,opt,name=sell_percentage,json=sellPercentage,proto3,oneof" json:"sell_percentage,omitempty"` // 跟卖百分比 (0-100)，当follow_sell为true时生效
	// 跟单条件
	MinPoolSize   *string `protobuf:"bytes,10,opt,name=min_pool_size,json=minPoolSize,proto3,oneof" json:"min_pool_size,omitempty"`    // 最小池子大小
	MaxPoolSize   *string `protobuf:"bytes,11,opt,name=max_pool_size,json=maxPoolSize,proto3,oneof" json:"max_pool_size,omitempty"`    // 最大池子大小
	MinBuyAmount  *string `protobuf:"bytes,12,opt,name=min_buy_amount,json=minBuyAmount,proto3,oneof" json:"min_buy_amount,omitempty"` // 目标地址最小买入金额
	MaxBuyAmount  *string `protobuf:"bytes,13,opt,name=max_buy_amount,json=maxBuyAmount,proto3,oneof" json:"max_buy_amount,omitempty"` // 目标地址最大买入金额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCopyOrderRequest) Reset() {
	*x = CreateCopyOrderRequest{}
	mi := &file_copy_v1_copy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCopyOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCopyOrderRequest) ProtoMessage() {}

func (x *CreateCopyOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_copy_v1_copy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCopyOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateCopyOrderRequest) Descriptor() ([]byte, []int) {
	return file_copy_v1_copy_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCopyOrderRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *CreateCopyOrderRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *CreateCopyOrderRequest) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *CreateCopyOrderRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *CreateCopyOrderRequest) GetBizOrderId() string {
	if x != nil {
		return x.BizOrderId
	}
	return ""
}

func (x *CreateCopyOrderRequest) GetCopyStrategy() isCreateCopyOrderRequest_CopyStrategy {
	if x != nil {
		return x.CopyStrategy
	}
	return nil
}

func (x *CreateCopyOrderRequest) GetFixedAmount() string {
	if x != nil {
		if x, ok := x.CopyStrategy.(*CreateCopyOrderRequest_FixedAmount); ok {
			return x.FixedAmount
		}
	}
	return ""
}

func (x *CreateCopyOrderRequest) GetPercentage() float64 {
	if x != nil {
		if x, ok := x.CopyStrategy.(*CreateCopyOrderRequest_Percentage); ok {
			return x.Percentage
		}
	}
	return 0
}

func (x *CreateCopyOrderRequest) GetFollowSell() bool {
	if x != nil {
		return x.FollowSell
	}
	return false
}

func (x *CreateCopyOrderRequest) GetSellPercentage() float64 {
	if x != nil && x.SellPercentage != nil {
		return *x.SellPercentage
	}
	return 0
}

func (x *CreateCopyOrderRequest) GetMinPoolSize() string {
	if x != nil && x.MinPoolSize != nil {
		return *x.MinPoolSize
	}
	return ""
}

func (x *CreateCopyOrderRequest) GetMaxPoolSize() string {
	if x != nil && x.MaxPoolSize != nil {
		return *x.MaxPoolSize
	}
	return ""
}

func (x *CreateCopyOrderRequest) GetMinBuyAmount() string {
	if x != nil && x.MinBuyAmount != nil {
		return *x.MinBuyAmount
	}
	return ""
}

func (x *CreateCopyOrderRequest) GetMaxBuyAmount() string {
	if x != nil && x.MaxBuyAmount != nil {
		return *x.MaxBuyAmount
	}
	return ""
}

type isCreateCopyOrderRequest_CopyStrategy interface {
	isCreateCopyOrderRequest_CopyStrategy()
}

type CreateCopyOrderRequest_FixedAmount struct {
	FixedAmount string `protobuf:"bytes,6,opt,name=fixed_amount,json=fixedAmount,proto3,oneof"` // 固定跟单金额
}

type CreateCopyOrderRequest_Percentage struct {
	Percentage float64 `protobuf:"fixed64,7,opt,name=percentage,proto3,oneof"` // 百分比跟单 (0-100)
}

func (*CreateCopyOrderRequest_FixedAmount) isCreateCopyOrderRequest_CopyStrategy() {}

func (*CreateCopyOrderRequest_Percentage) isCreateCopyOrderRequest_CopyStrategy() {}

type CopyAmountStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"` // 复制数量
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`   // 复制价格
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyAmountStrategy) Reset() {
	*x = CopyAmountStrategy{}
	mi := &file_copy_v1_copy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyAmountStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyAmountStrategy) ProtoMessage() {}

func (x *CopyAmountStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_copy_v1_copy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyAmountStrategy.ProtoReflect.Descriptor instead.
func (*CopyAmountStrategy) Descriptor() ([]byte, []int) {
	return file_copy_v1_copy_proto_rawDescGZIP(), []int{1}
}

func (x *CopyAmountStrategy) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CopyAmountStrategy) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

type CreateCopyOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCopyOrderReply) Reset() {
	*x = CreateCopyOrderReply{}
	mi := &file_copy_v1_copy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCopyOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCopyOrderReply) ProtoMessage() {}

func (x *CreateCopyOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_copy_v1_copy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCopyOrderReply.ProtoReflect.Descriptor instead.
func (*CreateCopyOrderReply) Descriptor() ([]byte, []int) {
	return file_copy_v1_copy_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCopyOrderReply) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_copy_v1_copy_proto protoreflect.FileDescriptor

const file_copy_v1_copy_proto_rawDesc = "" +
	"\n" +
	"\x12copy/v1/copy.proto\x12\vapi.copy.v1\"\xed\x04\n" +
	"\x16CreateCopyOrderRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12!\n" +
	"\fuser_address\x18\x02 \x01(\tR\vuserAddress\x12%\n" +
	"\x0etarget_address\x18\x03 \x01(\tR\rtargetAddress\x12\x1f\n" +
	"\vprivate_key\x18\x04 \x01(\tR\n" +
	"privateKey\x12 \n" +
	"\fbiz_order_id\x18\x05 \x01(\tR\n" +
	"bizOrderId\x12#\n" +
	"\ffixed_amount\x18\x06 \x01(\tH\x00R\vfixedAmount\x12 \n" +
	"\n" +
	"percentage\x18\a \x01(\x01H\x00R\n" +
	"percentage\x12\x1f\n" +
	"\vfollow_sell\x18\b \x01(\bR\n" +
	"followSell\x12,\n" +
	"\x0fsell_percentage\x18\t \x01(\x01H\x01R\x0esellPercentage\x88\x01\x01\x12'\n" +
	"\rmin_pool_size\x18\n" +
	" \x01(\tH\x02R\vminPoolSize\x88\x01\x01\x12'\n" +
	"\rmax_pool_size\x18\v \x01(\tH\x03R\vmaxPoolSize\x88\x01\x01\x12)\n" +
	"\x0emin_buy_amount\x18\f \x01(\tH\x04R\fminBuyAmount\x88\x01\x01\x12)\n" +
	"\x0emax_buy_amount\x18\r \x01(\tH\x05R\fmaxBuyAmount\x88\x01\x01B\x0f\n" +
	"\rcopy_strategyB\x12\n" +
	"\x10_sell_percentageB\x10\n" +
	"\x0e_min_pool_sizeB\x10\n" +
	"\x0e_max_pool_sizeB\x11\n" +
	"\x0f_min_buy_amountB\x11\n" +
	"\x0f_max_buy_amount\"B\n" +
	"\x12CopyAmountStrategy\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\"1\n" +
	"\x14CreateCopyOrderReply\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId2m\n" +
	"\x10CopyTradeService\x12Y\n" +
	"\x0fCreateCopyOrder\x12#.api.copy.v1.CreateCopyOrderRequest\x1a!.api.copy.v1.CreateCopyOrderReplyB%\n" +
	"\vapi.copy.v1P\x01Z\x14block/api/copy/v1;v1b\x06proto3"

var (
	file_copy_v1_copy_proto_rawDescOnce sync.Once
	file_copy_v1_copy_proto_rawDescData []byte
)

func file_copy_v1_copy_proto_rawDescGZIP() []byte {
	file_copy_v1_copy_proto_rawDescOnce.Do(func() {
		file_copy_v1_copy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_copy_v1_copy_proto_rawDesc), len(file_copy_v1_copy_proto_rawDesc)))
	})
	return file_copy_v1_copy_proto_rawDescData
}

var file_copy_v1_copy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_copy_v1_copy_proto_goTypes = []any{
	(*CreateCopyOrderRequest)(nil), // 0: api.copy.v1.CreateCopyOrderRequest
	(*CopyAmountStrategy)(nil),     // 1: api.copy.v1.CopyAmountStrategy
	(*CreateCopyOrderReply)(nil),   // 2: api.copy.v1.CreateCopyOrderReply
}
var file_copy_v1_copy_proto_depIdxs = []int32{
	0, // 0: api.copy.v1.CopyTradeService.CreateCopyOrder:input_type -> api.copy.v1.CreateCopyOrderRequest
	2, // 1: api.copy.v1.CopyTradeService.CreateCopyOrder:output_type -> api.copy.v1.CreateCopyOrderReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_copy_v1_copy_proto_init() }
func file_copy_v1_copy_proto_init() {
	if File_copy_v1_copy_proto != nil {
		return
	}
	file_copy_v1_copy_proto_msgTypes[0].OneofWrappers = []any{
		(*CreateCopyOrderRequest_FixedAmount)(nil),
		(*CreateCopyOrderRequest_Percentage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_copy_v1_copy_proto_rawDesc), len(file_copy_v1_copy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_copy_v1_copy_proto_goTypes,
		DependencyIndexes: file_copy_v1_copy_proto_depIdxs,
		MessageInfos:      file_copy_v1_copy_proto_msgTypes,
	}.Build()
	File_copy_v1_copy_proto = out.File
	file_copy_v1_copy_proto_goTypes = nil
	file_copy_v1_copy_proto_depIdxs = nil
}
