// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: network/v1/network.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetworkRequest) Reset() {
	*x = CreateNetworkRequest{}
	mi := &file_network_v1_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkRequest) ProtoMessage() {}

func (x *CreateNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkRequest.ProtoReflect.Descriptor instead.
func (*CreateNetworkRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{0}
}

type CreateNetworkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetworkReply) Reset() {
	*x = CreateNetworkReply{}
	mi := &file_network_v1_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetworkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkReply) ProtoMessage() {}

func (x *CreateNetworkReply) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkReply.ProtoReflect.Descriptor instead.
func (*CreateNetworkReply) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{1}
}

type UpdateNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNetworkRequest) Reset() {
	*x = UpdateNetworkRequest{}
	mi := &file_network_v1_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNetworkRequest) ProtoMessage() {}

func (x *UpdateNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNetworkRequest.ProtoReflect.Descriptor instead.
func (*UpdateNetworkRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{2}
}

type UpdateNetworkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNetworkReply) Reset() {
	*x = UpdateNetworkReply{}
	mi := &file_network_v1_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNetworkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNetworkReply) ProtoMessage() {}

func (x *UpdateNetworkReply) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNetworkReply.ProtoReflect.Descriptor instead.
func (*UpdateNetworkReply) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{3}
}

type DeleteNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkRequest) Reset() {
	*x = DeleteNetworkRequest{}
	mi := &file_network_v1_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkRequest) ProtoMessage() {}

func (x *DeleteNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkRequest.ProtoReflect.Descriptor instead.
func (*DeleteNetworkRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{4}
}

type DeleteNetworkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkReply) Reset() {
	*x = DeleteNetworkReply{}
	mi := &file_network_v1_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkReply) ProtoMessage() {}

func (x *DeleteNetworkReply) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkReply.ProtoReflect.Descriptor instead.
func (*DeleteNetworkReply) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{5}
}

type GetNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkRequest) Reset() {
	*x = GetNetworkRequest{}
	mi := &file_network_v1_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkRequest) ProtoMessage() {}

func (x *GetNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{6}
}

type GetNetworkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkReply) Reset() {
	*x = GetNetworkReply{}
	mi := &file_network_v1_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkReply) ProtoMessage() {}

func (x *GetNetworkReply) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkReply.ProtoReflect.Descriptor instead.
func (*GetNetworkReply) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{7}
}

type ListNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkRequest) Reset() {
	*x = ListNetworkRequest{}
	mi := &file_network_v1_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkRequest) ProtoMessage() {}

func (x *ListNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkRequest.ProtoReflect.Descriptor instead.
func (*ListNetworkRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{8}
}

type ListNetworkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Networks      []*NetworkItem         `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkReply) Reset() {
	*x = ListNetworkReply{}
	mi := &file_network_v1_network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkReply) ProtoMessage() {}

func (x *ListNetworkReply) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkReply.ProtoReflect.Descriptor instead.
func (*ListNetworkReply) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{9}
}

func (x *ListNetworkReply) GetNetworks() []*NetworkItem {
	if x != nil {
		return x.Networks
	}
	return nil
}

type NetworkItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkItem) Reset() {
	*x = NetworkItem{}
	mi := &file_network_v1_network_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkItem) ProtoMessage() {}

func (x *NetworkItem) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkItem.ProtoReflect.Descriptor instead.
func (*NetworkItem) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NetworkItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type ListNetworksByChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworksByChainRequest) Reset() {
	*x = ListNetworksByChainRequest{}
	mi := &file_network_v1_network_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworksByChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworksByChainRequest) ProtoMessage() {}

func (x *ListNetworksByChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworksByChainRequest.ProtoReflect.Descriptor instead.
func (*ListNetworksByChainRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{11}
}

func (x *ListNetworksByChainRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type ListNetworksByChainReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Networks      []*NetworkItem         `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworksByChainReply) Reset() {
	*x = ListNetworksByChainReply{}
	mi := &file_network_v1_network_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworksByChainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworksByChainReply) ProtoMessage() {}

func (x *ListNetworksByChainReply) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworksByChainReply.ProtoReflect.Descriptor instead.
func (*ListNetworksByChainReply) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{12}
}

func (x *ListNetworksByChainReply) GetNetworks() []*NetworkItem {
	if x != nil {
		return x.Networks
	}
	return nil
}

var File_network_v1_network_proto protoreflect.FileDescriptor

const file_network_v1_network_proto_rawDesc = "" +
	"\n" +
	"\x18network/v1/network.proto\x12\x0eapi.network.v1\"\x16\n" +
	"\x14CreateNetworkRequest\"\x14\n" +
	"\x12CreateNetworkReply\"\x16\n" +
	"\x14UpdateNetworkRequest\"\x14\n" +
	"\x12UpdateNetworkReply\"\x16\n" +
	"\x14DeleteNetworkRequest\"\x14\n" +
	"\x12DeleteNetworkReply\"\x13\n" +
	"\x11GetNetworkRequest\"\x11\n" +
	"\x0fGetNetworkReply\"\x14\n" +
	"\x12ListNetworkRequest\"K\n" +
	"\x10ListNetworkReply\x127\n" +
	"\bnetworks\x18\x01 \x03(\v2\x1b.api.network.v1.NetworkItemR\bnetworks\"I\n" +
	"\vNetworkItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\"7\n" +
	"\x1aListNetworksByChainRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\"S\n" +
	"\x18ListNetworksByChainReply\x127\n" +
	"\bnetworks\x18\x01 \x03(\v2\x1b.api.network.v1.NetworkItemR\bnetworks2\xae\x04\n" +
	"\aNetwork\x12Y\n" +
	"\rCreateNetwork\x12$.api.network.v1.CreateNetworkRequest\x1a\".api.network.v1.CreateNetworkReply\x12Y\n" +
	"\rUpdateNetwork\x12$.api.network.v1.UpdateNetworkRequest\x1a\".api.network.v1.UpdateNetworkReply\x12Y\n" +
	"\rDeleteNetwork\x12$.api.network.v1.DeleteNetworkRequest\x1a\".api.network.v1.DeleteNetworkReply\x12P\n" +
	"\n" +
	"GetNetwork\x12!.api.network.v1.GetNetworkRequest\x1a\x1f.api.network.v1.GetNetworkReply\x12S\n" +
	"\vListNetwork\x12\".api.network.v1.ListNetworkRequest\x1a .api.network.v1.ListNetworkReply\x12k\n" +
	"\x13ListNetworksByChain\x12*.api.network.v1.ListNetworksByChainRequest\x1a(.api.network.v1.ListNetworksByChainReplyB+\n" +
	"\x0eapi.network.v1P\x01Z\x17block/api/network/v1;v1b\x06proto3"

var (
	file_network_v1_network_proto_rawDescOnce sync.Once
	file_network_v1_network_proto_rawDescData []byte
)

func file_network_v1_network_proto_rawDescGZIP() []byte {
	file_network_v1_network_proto_rawDescOnce.Do(func() {
		file_network_v1_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_v1_network_proto_rawDesc), len(file_network_v1_network_proto_rawDesc)))
	})
	return file_network_v1_network_proto_rawDescData
}

var file_network_v1_network_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_network_v1_network_proto_goTypes = []any{
	(*CreateNetworkRequest)(nil),       // 0: api.network.v1.CreateNetworkRequest
	(*CreateNetworkReply)(nil),         // 1: api.network.v1.CreateNetworkReply
	(*UpdateNetworkRequest)(nil),       // 2: api.network.v1.UpdateNetworkRequest
	(*UpdateNetworkReply)(nil),         // 3: api.network.v1.UpdateNetworkReply
	(*DeleteNetworkRequest)(nil),       // 4: api.network.v1.DeleteNetworkRequest
	(*DeleteNetworkReply)(nil),         // 5: api.network.v1.DeleteNetworkReply
	(*GetNetworkRequest)(nil),          // 6: api.network.v1.GetNetworkRequest
	(*GetNetworkReply)(nil),            // 7: api.network.v1.GetNetworkReply
	(*ListNetworkRequest)(nil),         // 8: api.network.v1.ListNetworkRequest
	(*ListNetworkReply)(nil),           // 9: api.network.v1.ListNetworkReply
	(*NetworkItem)(nil),                // 10: api.network.v1.NetworkItem
	(*ListNetworksByChainRequest)(nil), // 11: api.network.v1.ListNetworksByChainRequest
	(*ListNetworksByChainReply)(nil),   // 12: api.network.v1.ListNetworksByChainReply
}
var file_network_v1_network_proto_depIdxs = []int32{
	10, // 0: api.network.v1.ListNetworkReply.networks:type_name -> api.network.v1.NetworkItem
	10, // 1: api.network.v1.ListNetworksByChainReply.networks:type_name -> api.network.v1.NetworkItem
	0,  // 2: api.network.v1.Network.CreateNetwork:input_type -> api.network.v1.CreateNetworkRequest
	2,  // 3: api.network.v1.Network.UpdateNetwork:input_type -> api.network.v1.UpdateNetworkRequest
	4,  // 4: api.network.v1.Network.DeleteNetwork:input_type -> api.network.v1.DeleteNetworkRequest
	6,  // 5: api.network.v1.Network.GetNetwork:input_type -> api.network.v1.GetNetworkRequest
	8,  // 6: api.network.v1.Network.ListNetwork:input_type -> api.network.v1.ListNetworkRequest
	11, // 7: api.network.v1.Network.ListNetworksByChain:input_type -> api.network.v1.ListNetworksByChainRequest
	1,  // 8: api.network.v1.Network.CreateNetwork:output_type -> api.network.v1.CreateNetworkReply
	3,  // 9: api.network.v1.Network.UpdateNetwork:output_type -> api.network.v1.UpdateNetworkReply
	5,  // 10: api.network.v1.Network.DeleteNetwork:output_type -> api.network.v1.DeleteNetworkReply
	7,  // 11: api.network.v1.Network.GetNetwork:output_type -> api.network.v1.GetNetworkReply
	9,  // 12: api.network.v1.Network.ListNetwork:output_type -> api.network.v1.ListNetworkReply
	12, // 13: api.network.v1.Network.ListNetworksByChain:output_type -> api.network.v1.ListNetworksByChainReply
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_network_v1_network_proto_init() }
func file_network_v1_network_proto_init() {
	if File_network_v1_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_v1_network_proto_rawDesc), len(file_network_v1_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_v1_network_proto_goTypes,
		DependencyIndexes: file_network_v1_network_proto_depIdxs,
		MessageInfos:      file_network_v1_network_proto_msgTypes,
	}.Build()
	File_network_v1_network_proto = out.File
	file_network_v1_network_proto_goTypes = nil
	file_network_v1_network_proto_depIdxs = nil
}
