// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sub/v1/reef_sub_service_sol.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 订阅交易请求
type SubscribeTradeRequestSol struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 代币 mint 地址
	MintAddress   string `protobuf:"bytes,1,opt,name=mint_address,json=mintAddress,proto3" json:"mint_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTradeRequestSol) Reset() {
	*x = SubscribeTradeRequestSol{}
	mi := &file_sub_v1_reef_sub_service_sol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTradeRequestSol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTradeRequestSol) ProtoMessage() {}

func (x *SubscribeTradeRequestSol) ProtoReflect() protoreflect.Message {
	mi := &file_sub_v1_reef_sub_service_sol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTradeRequestSol.ProtoReflect.Descriptor instead.
func (*SubscribeTradeRequestSol) Descriptor() ([]byte, []int) {
	return file_sub_v1_reef_sub_service_sol_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeTradeRequestSol) GetMintAddress() string {
	if x != nil {
		return x.MintAddress
	}
	return ""
}

// 订阅最新交易请求（空请求）
type SubscribeLatestTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeLatestTradeRequest) Reset() {
	*x = SubscribeLatestTradeRequest{}
	mi := &file_sub_v1_reef_sub_service_sol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeLatestTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeLatestTradeRequest) ProtoMessage() {}

func (x *SubscribeLatestTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sub_v1_reef_sub_service_sol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeLatestTradeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeLatestTradeRequest) Descriptor() ([]byte, []int) {
	return file_sub_v1_reef_sub_service_sol_proto_rawDescGZIP(), []int{1}
}

// 交易响应
type TradeResponseSol struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 交易签名
	Signature string `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// 用户地址
	UserAddress string `protobuf:"bytes,2,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	// 输入代币 mint 地址
	InputMint string `protobuf:"bytes,3,opt,name=input_mint,json=inputMint,proto3" json:"input_mint,omitempty"`
	// 输出代币 mint 地址
	OutputMint string `protobuf:"bytes,4,opt,name=output_mint,json=outputMint,proto3" json:"output_mint,omitempty"`
	// 输入数量
	InputAmount uint64 `protobuf:"varint,5,opt,name=input_amount,json=inputAmount,proto3" json:"input_amount,omitempty"`
	// 输出数量
	OutputAmount uint64 `protobuf:"varint,6,opt,name=output_amount,json=outputAmount,proto3" json:"output_amount,omitempty"`
	// 交易类型 (买入/卖出)
	TradeType string `protobuf:"bytes,7,opt,name=trade_type,json=tradeType,proto3" json:"trade_type,omitempty"`
	// 时间戳
	Timestamp int64 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 池地址
	PoolAddress   string `protobuf:"bytes,9,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeResponseSol) Reset() {
	*x = TradeResponseSol{}
	mi := &file_sub_v1_reef_sub_service_sol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeResponseSol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeResponseSol) ProtoMessage() {}

func (x *TradeResponseSol) ProtoReflect() protoreflect.Message {
	mi := &file_sub_v1_reef_sub_service_sol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeResponseSol.ProtoReflect.Descriptor instead.
func (*TradeResponseSol) Descriptor() ([]byte, []int) {
	return file_sub_v1_reef_sub_service_sol_proto_rawDescGZIP(), []int{2}
}

func (x *TradeResponseSol) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *TradeResponseSol) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *TradeResponseSol) GetInputMint() string {
	if x != nil {
		return x.InputMint
	}
	return ""
}

func (x *TradeResponseSol) GetOutputMint() string {
	if x != nil {
		return x.OutputMint
	}
	return ""
}

func (x *TradeResponseSol) GetInputAmount() uint64 {
	if x != nil {
		return x.InputAmount
	}
	return 0
}

func (x *TradeResponseSol) GetOutputAmount() uint64 {
	if x != nil {
		return x.OutputAmount
	}
	return 0
}

func (x *TradeResponseSol) GetTradeType() string {
	if x != nil {
		return x.TradeType
	}
	return ""
}

func (x *TradeResponseSol) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TradeResponseSol) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

var File_sub_v1_reef_sub_service_sol_proto protoreflect.FileDescriptor

const file_sub_v1_reef_sub_service_sol_proto_rawDesc = "" +
	"\n" +
	"!sub/v1/reef_sub_service_sol.proto\x12\rtrade_service\"=\n" +
	"\x18SubscribeTradeRequestSol\x12!\n" +
	"\fmint_address\x18\x01 \x01(\tR\vmintAddress\"\x1d\n" +
	"\x1bSubscribeLatestTradeRequest\"\xbb\x02\n" +
	"\x10TradeResponseSol\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12!\n" +
	"\fuser_address\x18\x02 \x01(\tR\vuserAddress\x12\x1d\n" +
	"\n" +
	"input_mint\x18\x03 \x01(\tR\tinputMint\x12\x1f\n" +
	"\voutput_mint\x18\x04 \x01(\tR\n" +
	"outputMint\x12!\n" +
	"\finput_amount\x18\x05 \x01(\x04R\vinputAmount\x12#\n" +
	"\routput_amount\x18\x06 \x01(\x04R\foutputAmount\x12\x1d\n" +
	"\n" +
	"trade_type\x18\a \x01(\tR\ttradeType\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12!\n" +
	"\fpool_address\x18\t \x01(\tR\vpoolAddress2\xdb\x01\n" +
	"\x0fTradeServiceSol\x12a\n" +
	"\x11SubscribeTradeSol\x12'.trade_service.SubscribeTradeRequestSol\x1a\x1f.trade_service.TradeResponseSol(\x010\x01\x12e\n" +
	"\x14SubscribeLatestTrade\x12*.trade_service.SubscribeLatestTradeRequest\x1a\x1f.trade_service.TradeResponseSol0\x01Bf\n" +
	"\x1fdev.kratos.api.trade_service.v1B\x13TradeServiceProtoV1P\x01Z,reef_sub_service_sol/api/trade_service/v1;v1b\x06proto3"

var (
	file_sub_v1_reef_sub_service_sol_proto_rawDescOnce sync.Once
	file_sub_v1_reef_sub_service_sol_proto_rawDescData []byte
)

func file_sub_v1_reef_sub_service_sol_proto_rawDescGZIP() []byte {
	file_sub_v1_reef_sub_service_sol_proto_rawDescOnce.Do(func() {
		file_sub_v1_reef_sub_service_sol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sub_v1_reef_sub_service_sol_proto_rawDesc), len(file_sub_v1_reef_sub_service_sol_proto_rawDesc)))
	})
	return file_sub_v1_reef_sub_service_sol_proto_rawDescData
}

var file_sub_v1_reef_sub_service_sol_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sub_v1_reef_sub_service_sol_proto_goTypes = []any{
	(*SubscribeTradeRequestSol)(nil),    // 0: trade_service.SubscribeTradeRequestSol
	(*SubscribeLatestTradeRequest)(nil), // 1: trade_service.SubscribeLatestTradeRequest
	(*TradeResponseSol)(nil),            // 2: trade_service.TradeResponseSol
}
var file_sub_v1_reef_sub_service_sol_proto_depIdxs = []int32{
	0, // 0: trade_service.TradeServiceSol.SubscribeTradeSol:input_type -> trade_service.SubscribeTradeRequestSol
	1, // 1: trade_service.TradeServiceSol.SubscribeLatestTrade:input_type -> trade_service.SubscribeLatestTradeRequest
	2, // 2: trade_service.TradeServiceSol.SubscribeTradeSol:output_type -> trade_service.TradeResponseSol
	2, // 3: trade_service.TradeServiceSol.SubscribeLatestTrade:output_type -> trade_service.TradeResponseSol
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sub_v1_reef_sub_service_sol_proto_init() }
func file_sub_v1_reef_sub_service_sol_proto_init() {
	if File_sub_v1_reef_sub_service_sol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sub_v1_reef_sub_service_sol_proto_rawDesc), len(file_sub_v1_reef_sub_service_sol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sub_v1_reef_sub_service_sol_proto_goTypes,
		DependencyIndexes: file_sub_v1_reef_sub_service_sol_proto_depIdxs,
		MessageInfos:      file_sub_v1_reef_sub_service_sol_proto_msgTypes,
	}.Build()
	File_sub_v1_reef_sub_service_sol_proto = out.File
	file_sub_v1_reef_sub_service_sol_proto_goTypes = nil
	file_sub_v1_reef_sub_service_sol_proto_depIdxs = nil
}
