// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sub/v1/reef_sub_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支持的区块链类型
type Chain int32

const (
	Chain_SOL Chain = 0 // Solana
	Chain_BSC Chain = 1 // Binance Smart Chain
)

// Enum value maps for Chain.
var (
	Chain_name = map[int32]string{
		0: "SOL",
		1: "BSC",
	}
	Chain_value = map[string]int32{
		"SOL": 0,
		"BSC": 1,
	}
)

func (x Chain) Enum() *Chain {
	p := new(Chain)
	*p = x
	return p
}

func (x Chain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Chain) Descriptor() protoreflect.EnumDescriptor {
	return file_sub_v1_reef_sub_service_proto_enumTypes[0].Descriptor()
}

func (Chain) Type() protoreflect.EnumType {
	return &file_sub_v1_reef_sub_service_proto_enumTypes[0]
}

func (x Chain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Chain.Descriptor instead.
func (Chain) EnumDescriptor() ([]byte, []int) {
	return file_sub_v1_reef_sub_service_proto_rawDescGZIP(), []int{0}
}

// 订阅交易请求
type SubscribeTradeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 代币地址（SOL为mint地址，BSC为合约地址）
	TokenAddress string `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	// 区块链类型
	Chain         Chain `protobuf:"varint,2,opt,name=chain,proto3,enum=trade_service.Chain" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTradeRequest) Reset() {
	*x = SubscribeTradeRequest{}
	mi := &file_sub_v1_reef_sub_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTradeRequest) ProtoMessage() {}

func (x *SubscribeTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sub_v1_reef_sub_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTradeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTradeRequest) Descriptor() ([]byte, []int) {
	return file_sub_v1_reef_sub_service_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeTradeRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *SubscribeTradeRequest) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_SOL
}

// 订阅最新交易请求
type SubscribeLatestTradeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 区块链类型
	Chain         Chain `protobuf:"varint,1,opt,name=chain,proto3,enum=trade_service.Chain" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeLatestTradeRequest) Reset() {
	*x = SubscribeLatestTradeRequest{}
	mi := &file_sub_v1_reef_sub_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeLatestTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeLatestTradeRequest) ProtoMessage() {}

func (x *SubscribeLatestTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sub_v1_reef_sub_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeLatestTradeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeLatestTradeRequest) Descriptor() ([]byte, []int) {
	return file_sub_v1_reef_sub_service_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeLatestTradeRequest) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_SOL
}

// 交易响应
type TradeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 交易签名/哈希
	Signature string `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// 用户地址
	UserAddress string `protobuf:"bytes,2,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	// 输入代币地址
	InputAddress string `protobuf:"bytes,3,opt,name=input_address,json=inputAddress,proto3" json:"input_address,omitempty"`
	// 输出代币地址
	OutputAddress string `protobuf:"bytes,4,opt,name=output_address,json=outputAddress,proto3" json:"output_address,omitempty"`
	// 输入数量
	InputAmount string `protobuf:"bytes,5,opt,name=input_amount,json=inputAmount,proto3" json:"input_amount,omitempty"` // 使用string避免精度问题
	// 输出数量
	OutputAmount string `protobuf:"bytes,6,opt,name=output_amount,json=outputAmount,proto3" json:"output_amount,omitempty"` // 使用string避免精度问题
	// 交易类型 (买入/卖出)
	TradeType string `protobuf:"bytes,7,opt,name=trade_type,json=tradeType,proto3" json:"trade_type,omitempty"`
	// 时间戳
	Timestamp int64 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 池地址
	PoolAddress string `protobuf:"bytes,9,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	// 区块链类型
	Chain         Chain `protobuf:"varint,10,opt,name=chain,proto3,enum=trade_service.Chain" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeResponse) Reset() {
	*x = TradeResponse{}
	mi := &file_sub_v1_reef_sub_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeResponse) ProtoMessage() {}

func (x *TradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sub_v1_reef_sub_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeResponse.ProtoReflect.Descriptor instead.
func (*TradeResponse) Descriptor() ([]byte, []int) {
	return file_sub_v1_reef_sub_service_proto_rawDescGZIP(), []int{2}
}

func (x *TradeResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *TradeResponse) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *TradeResponse) GetInputAddress() string {
	if x != nil {
		return x.InputAddress
	}
	return ""
}

func (x *TradeResponse) GetOutputAddress() string {
	if x != nil {
		return x.OutputAddress
	}
	return ""
}

func (x *TradeResponse) GetInputAmount() string {
	if x != nil {
		return x.InputAmount
	}
	return ""
}

func (x *TradeResponse) GetOutputAmount() string {
	if x != nil {
		return x.OutputAmount
	}
	return ""
}

func (x *TradeResponse) GetTradeType() string {
	if x != nil {
		return x.TradeType
	}
	return ""
}

func (x *TradeResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TradeResponse) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

func (x *TradeResponse) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_SOL
}

var File_sub_v1_reef_sub_service_proto protoreflect.FileDescriptor

const file_sub_v1_reef_sub_service_proto_rawDesc = "" +
	"\n" +
	"\x1dsub/v1/reef_sub_service.proto\x12\rtrade_service\"h\n" +
	"\x15SubscribeTradeRequest\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12*\n" +
	"\x05chain\x18\x02 \x01(\x0e2\x14.trade_service.ChainR\x05chain\"I\n" +
	"\x1bSubscribeLatestTradeRequest\x12*\n" +
	"\x05chain\x18\x01 \x01(\x0e2\x14.trade_service.ChainR\x05chain\"\xf0\x02\n" +
	"\rTradeResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12!\n" +
	"\fuser_address\x18\x02 \x01(\tR\vuserAddress\x12#\n" +
	"\rinput_address\x18\x03 \x01(\tR\finputAddress\x12%\n" +
	"\x0eoutput_address\x18\x04 \x01(\tR\routputAddress\x12!\n" +
	"\finput_amount\x18\x05 \x01(\tR\vinputAmount\x12#\n" +
	"\routput_amount\x18\x06 \x01(\tR\foutputAmount\x12\x1d\n" +
	"\n" +
	"trade_type\x18\a \x01(\tR\ttradeType\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12!\n" +
	"\fpool_address\x18\t \x01(\tR\vpoolAddress\x12*\n" +
	"\x05chain\x18\n" +
	" \x01(\x0e2\x14.trade_service.ChainR\x05chain*\x19\n" +
	"\x05Chain\x12\a\n" +
	"\x03SOL\x10\x00\x12\a\n" +
	"\x03BSC\x10\x012\xcc\x01\n" +
	"\fTradeService\x12X\n" +
	"\x0eSubscribeTrade\x12$.trade_service.SubscribeTradeRequest\x1a\x1c.trade_service.TradeResponse(\x010\x01\x12b\n" +
	"\x14SubscribeLatestTrade\x12*.trade_service.SubscribeLatestTradeRequest\x1a\x1c.trade_service.TradeResponse0\x01Bf\n" +
	"\x1fdev.kratos.api.trade_service.v1B\x13TradeServiceProtoV1P\x01Z,reef_sub_service_sol/api/trade_service/v1;v1b\x06proto3"

var (
	file_sub_v1_reef_sub_service_proto_rawDescOnce sync.Once
	file_sub_v1_reef_sub_service_proto_rawDescData []byte
)

func file_sub_v1_reef_sub_service_proto_rawDescGZIP() []byte {
	file_sub_v1_reef_sub_service_proto_rawDescOnce.Do(func() {
		file_sub_v1_reef_sub_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sub_v1_reef_sub_service_proto_rawDesc), len(file_sub_v1_reef_sub_service_proto_rawDesc)))
	})
	return file_sub_v1_reef_sub_service_proto_rawDescData
}

var file_sub_v1_reef_sub_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sub_v1_reef_sub_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sub_v1_reef_sub_service_proto_goTypes = []any{
	(Chain)(0),                          // 0: trade_service.Chain
	(*SubscribeTradeRequest)(nil),       // 1: trade_service.SubscribeTradeRequest
	(*SubscribeLatestTradeRequest)(nil), // 2: trade_service.SubscribeLatestTradeRequest
	(*TradeResponse)(nil),               // 3: trade_service.TradeResponse
}
var file_sub_v1_reef_sub_service_proto_depIdxs = []int32{
	0, // 0: trade_service.SubscribeTradeRequest.chain:type_name -> trade_service.Chain
	0, // 1: trade_service.SubscribeLatestTradeRequest.chain:type_name -> trade_service.Chain
	0, // 2: trade_service.TradeResponse.chain:type_name -> trade_service.Chain
	1, // 3: trade_service.TradeService.SubscribeTrade:input_type -> trade_service.SubscribeTradeRequest
	2, // 4: trade_service.TradeService.SubscribeLatestTrade:input_type -> trade_service.SubscribeLatestTradeRequest
	3, // 5: trade_service.TradeService.SubscribeTrade:output_type -> trade_service.TradeResponse
	3, // 6: trade_service.TradeService.SubscribeLatestTrade:output_type -> trade_service.TradeResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sub_v1_reef_sub_service_proto_init() }
func file_sub_v1_reef_sub_service_proto_init() {
	if File_sub_v1_reef_sub_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sub_v1_reef_sub_service_proto_rawDesc), len(file_sub_v1_reef_sub_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sub_v1_reef_sub_service_proto_goTypes,
		DependencyIndexes: file_sub_v1_reef_sub_service_proto_depIdxs,
		EnumInfos:         file_sub_v1_reef_sub_service_proto_enumTypes,
		MessageInfos:      file_sub_v1_reef_sub_service_proto_msgTypes,
	}.Build()
	File_sub_v1_reef_sub_service_proto = out.File
	file_sub_v1_reef_sub_service_proto_goTypes = nil
	file_sub_v1_reef_sub_service_proto_depIdxs = nil
}
