// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: chain/v1/chain.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChainRequest) Reset() {
	*x = CreateChainRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChainRequest) ProtoMessage() {}

func (x *CreateChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChainRequest.ProtoReflect.Descriptor instead.
func (*CreateChainRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChainRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type CreateChainReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChainReply) Reset() {
	*x = CreateChainReply{}
	mi := &file_chain_v1_chain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChainReply) ProtoMessage() {}

func (x *CreateChainReply) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChainReply.ProtoReflect.Descriptor instead.
func (*CreateChainReply) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{1}
}

type UpdateChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChainRequest) Reset() {
	*x = UpdateChainRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChainRequest) ProtoMessage() {}

func (x *UpdateChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChainRequest.ProtoReflect.Descriptor instead.
func (*UpdateChainRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{2}
}

type UpdateChainReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChainReply) Reset() {
	*x = UpdateChainReply{}
	mi := &file_chain_v1_chain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChainReply) ProtoMessage() {}

func (x *UpdateChainReply) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChainReply.ProtoReflect.Descriptor instead.
func (*UpdateChainReply) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{3}
}

type DeleteChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChainRequest) Reset() {
	*x = DeleteChainRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChainRequest) ProtoMessage() {}

func (x *DeleteChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChainRequest.ProtoReflect.Descriptor instead.
func (*DeleteChainRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{4}
}

type DeleteChainReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChainReply) Reset() {
	*x = DeleteChainReply{}
	mi := &file_chain_v1_chain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChainReply) ProtoMessage() {}

func (x *DeleteChainReply) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChainReply.ProtoReflect.Descriptor instead.
func (*DeleteChainReply) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{5}
}

type GetChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChainRequest) Reset() {
	*x = GetChainRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainRequest) ProtoMessage() {}

func (x *GetChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainRequest.ProtoReflect.Descriptor instead.
func (*GetChainRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{6}
}

type GetChainReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChainReply) Reset() {
	*x = GetChainReply{}
	mi := &file_chain_v1_chain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainReply) ProtoMessage() {}

func (x *GetChainReply) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainReply.ProtoReflect.Descriptor instead.
func (*GetChainReply) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{7}
}

type ListChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChainRequest) Reset() {
	*x = ListChainRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChainRequest) ProtoMessage() {}

func (x *ListChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChainRequest.ProtoReflect.Descriptor instead.
func (*ListChainRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{8}
}

type ListChainReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chains        []*ChainItem           `protobuf:"bytes,1,rep,name=chains,proto3" json:"chains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChainReply) Reset() {
	*x = ListChainReply{}
	mi := &file_chain_v1_chain_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChainReply) ProtoMessage() {}

func (x *ListChainReply) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChainReply.ProtoReflect.Descriptor instead.
func (*ListChainReply) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{9}
}

func (x *ListChainReply) GetChains() []*ChainItem {
	if x != nil {
		return x.Chains
	}
	return nil
}

type ChainItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainItem) Reset() {
	*x = ChainItem{}
	mi := &file_chain_v1_chain_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainItem) ProtoMessage() {}

func (x *ChainItem) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainItem.ProtoReflect.Descriptor instead.
func (*ChainItem) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{10}
}

func (x *ChainItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChainItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChainItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

var File_chain_v1_chain_proto protoreflect.FileDescriptor

var file_chain_v1_chain_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x22, 0x40, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x11,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x41, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x06, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x22, 0x47, 0x0a, 0x09, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x32, 0x8d, 0x03, 0x0a, 0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x4f, 0x0a, 0x0b,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x20, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4f, 0x0a,
	0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x20, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4f,
	0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x20, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x46, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x27, 0x0a, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x50, 0x01, 0x5a, 0x15, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_chain_v1_chain_proto_rawDescOnce sync.Once
	file_chain_v1_chain_proto_rawDescData []byte
)

func file_chain_v1_chain_proto_rawDescGZIP() []byte {
	file_chain_v1_chain_proto_rawDescOnce.Do(func() {
		file_chain_v1_chain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chain_v1_chain_proto_rawDesc), len(file_chain_v1_chain_proto_rawDesc)))
	})
	return file_chain_v1_chain_proto_rawDescData
}

var file_chain_v1_chain_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_chain_v1_chain_proto_goTypes = []any{
	(*CreateChainRequest)(nil), // 0: api.chain.v1.CreateChainRequest
	(*CreateChainReply)(nil),   // 1: api.chain.v1.CreateChainReply
	(*UpdateChainRequest)(nil), // 2: api.chain.v1.UpdateChainRequest
	(*UpdateChainReply)(nil),   // 3: api.chain.v1.UpdateChainReply
	(*DeleteChainRequest)(nil), // 4: api.chain.v1.DeleteChainRequest
	(*DeleteChainReply)(nil),   // 5: api.chain.v1.DeleteChainReply
	(*GetChainRequest)(nil),    // 6: api.chain.v1.GetChainRequest
	(*GetChainReply)(nil),      // 7: api.chain.v1.GetChainReply
	(*ListChainRequest)(nil),   // 8: api.chain.v1.ListChainRequest
	(*ListChainReply)(nil),     // 9: api.chain.v1.ListChainReply
	(*ChainItem)(nil),          // 10: api.chain.v1.ChainItem
}
var file_chain_v1_chain_proto_depIdxs = []int32{
	10, // 0: api.chain.v1.ListChainReply.chains:type_name -> api.chain.v1.ChainItem
	0,  // 1: api.chain.v1.Chain.CreateChain:input_type -> api.chain.v1.CreateChainRequest
	2,  // 2: api.chain.v1.Chain.UpdateChain:input_type -> api.chain.v1.UpdateChainRequest
	4,  // 3: api.chain.v1.Chain.DeleteChain:input_type -> api.chain.v1.DeleteChainRequest
	6,  // 4: api.chain.v1.Chain.GetChain:input_type -> api.chain.v1.GetChainRequest
	8,  // 5: api.chain.v1.Chain.ListChain:input_type -> api.chain.v1.ListChainRequest
	1,  // 6: api.chain.v1.Chain.CreateChain:output_type -> api.chain.v1.CreateChainReply
	3,  // 7: api.chain.v1.Chain.UpdateChain:output_type -> api.chain.v1.UpdateChainReply
	5,  // 8: api.chain.v1.Chain.DeleteChain:output_type -> api.chain.v1.DeleteChainReply
	7,  // 9: api.chain.v1.Chain.GetChain:output_type -> api.chain.v1.GetChainReply
	9,  // 10: api.chain.v1.Chain.ListChain:output_type -> api.chain.v1.ListChainReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_chain_v1_chain_proto_init() }
func file_chain_v1_chain_proto_init() {
	if File_chain_v1_chain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chain_v1_chain_proto_rawDesc), len(file_chain_v1_chain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chain_v1_chain_proto_goTypes,
		DependencyIndexes: file_chain_v1_chain_proto_depIdxs,
		MessageInfos:      file_chain_v1_chain_proto_msgTypes,
	}.Build()
	File_chain_v1_chain_proto = out.File
	file_chain_v1_chain_proto_goTypes = nil
	file_chain_v1_chain_proto_depIdxs = nil
}
